### PR TITLE
work in progress

### PR DESCRIPTION
**Pull request by Morturg**
created most of the new materials from AoN, rearranged some others to be alphabetical, stripped out things I put in before, fixed some of my own typos
added some descriptions up to lazurite before getting bored

### CODE REVIEW

**Comment by Morturg** [comment]
I'd wait for me to finish copying the rest from AoN before taking a look, just somethings I added today

need to decide if include the HP/hardness information in the text

I did up to lazurite, because if someone's not using the durability ext, then, they might want it...

**Comment by Morturg** [comment]
ok, think that's all the materials I can officially source right now (a few are named differently , d20pfsrd to AoN, so used AoN, as authority 

(one or two materials were also NOT on AoN, but found their source in adventure paths)

two of these are for non weapon/armor, I included for completeness, but maybe talk about whether they should be here or not

the irespan basalt, and the serpentstone, I think they can only be for objects, BUT, since they're not given = true for armor or weapons, it shouldn't come up just now

- what will come up, is individual cost/pricing
- some of these materials do not follow magic upgrade material convention, and have listed prices
- some do not require magic enhancement 
- I'm happy to make an array or something, depends on how you want to handle it, some are size, some are type some are just fixed, some are +50% or +75% 

- right now, just selecting these materials wont add any power or ability, and the price would be wrong, but at least the text is right, probably wise to hold off implementing a release as such until the corresponding low hanging fruit can also be attached: correct pricing/easy abilities (armor check, bonuses, etc)

**Comment by bmos** [comment]
sorry, I moved the data arrays into another file (since it takes up thousands of lines) which means this will need rework before it can be finished :(

**Comment by bmos** [comment]
I went ahead and started merging some of this in manually due to conflicts.
https://github.com/FG-Unofficial-Developers-Guild/FG-PFRPG-Customized-Item-Generator/compare/v1.13-hotfix.2...bae944fad93e926f3236e82b11d13c9d6549834d

**Pull request closed without merging**
